alphabetic:
  iPad:
    floating: "alphabetic_26_portrait"
    landscape: "alphabetic_26_landscape"
    portrait: "alphabetic_26_landscape"
  iPhone:
    landscape: "alphabetic_26_landscape"
    portrait: "alphabetic_26_portrait"
author: "斯文扫地"
name: "送你一朵小花-大字体"
numeric:
  iPad:
    floating: "numeric_9_portrait"
    landscape: "numeric_9_landscape"
    portrait: "numeric_9_portrait"
  iPhone:
    landscape: "numeric_9_landscape"
    portrait: "numeric_9_portrait"
panel:
  iPhone:
    landscape: "panel_landscape"
    portrait: "panel_portrait"
pinyin:
  iPad:
    floating: "pinyin_26_portrait"
    landscape: "pinyin_26_landscape"
    portrait: "pinyin_26_landscape"
  iPhone:
    landscape: "pinyin_26_landscape"
    portrait: "pinyin_26_portrait"
symbolic:
  iPad:
    floating: "symbolic_portrait"
    landscape: "numeric_9_landscape"
    portrait: "symbolic_portrait"
  iPhone:
    landscape: "numeric_9_landscape"
    portrait: "symbolic_portrait"